# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glide < Formula
  desc "A Lightweight, Cloud-Native LLM Gateway"
  homepage "https://github.com/EinStack/glide"
  version "0.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/einstack/glide/releases/download/0.0.1/glide_v0.0.1_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "4b2d1686762ea1fe6399a7b77edf37342425155db9714d61890213445e3405ec"

      def install
        bin.install "glide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/einstack/glide/releases/download/0.0.1/glide_v0.0.1_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3562be98698aa336639e178595fee2f7a5f646788838bb5c2022ed95e18ba936"

      def install
        bin.install "glide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/einstack/glide/releases/download/0.0.1/glide_v0.0.1_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b9eef2729b89580d00c71c2f5e752dbd47d60f485773142edb0e7cd75e88f862"

      def install
        bin.install "glide"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/einstack/glide/releases/download/0.0.1/glide_v0.0.1_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "e3896754b2c5d52aa72d1aa4bc9d29368fc10886c2cc95b9e69e27e22b9abfdb"

      def install
        bin.install "glide"
      end
    end
  end
end
